### PR TITLE
fix bugs

### PR DESCRIPTION
**Pull request by slowkow**
There are multiple issues fixed by this PR.

- `"GRCh38"` is not used as a key, so `data.get_data("GRCh38")` fails. It needs to be `data.get_data("GRCh38-rna")`. And `data.get_data("hashing-hashing")`.

- `np.log10(x)` should be `np.log10(1 + x)` to avoid errors.

- `zarr_zipstore = True` is not a valid argument for `pegasusio.write_output()`

### CODE REVIEW

**Comment by yihming** [comment]
These are due to the inconsistency with latest PegasusIO API. Thank you for bringing it up!

Our way of fixing these bugs tries to follow PegasusIO API, which is thus different from this pull request. Please see [here](https://github.com/klarman-cell-observatory/demuxEM/pull/5) for details.

For your second point, in the hashtag CSV generated by [cumulus_feature_barcoding](https://github.com/klarman-cell-observatory/cumulus_feature_barcoding), it is impossible to have any cell with summation 0 when feeding to `np.log10`.

**Comment by slowkow** [comment]
I created this issue is because demuxEM failed with a matrix generated by [cumulus_adt].

Please consider re-opening this issue and addressing the bug that I mentioned. Here are some options for you to consider:

1. Use `log10(1 + x)`.
2. Change the code to discard cells with 0 sum.

[cumulus_adt]: https://portal.firecloud.org/?return=terra#methods/cumulus/cumulus_adt/6/wdl

**Comment by bli25broad** [comment]
@slowkow , can you share a CSV file generated by cumulus_adt that can trigger the error?  By design, cumulus_adt will not report  a cell barcode with 0 UMIs.

Thanks,
Bo

**Comment by slowkow** [comment]
https://job-manager.dsde-prod.broadinstitute.org/jobs/dc1de87c-9caa-47ae-9a8b-0e346cba2d32

```
gs://fc-545c2194-e71d-4ff5-be80-7f12f101e9b7/batch_1-4_5p/data_output/batch1_5p_adt
```

```bash
csv=batch1_5p_adt.csv.gz
hto=${csv%.csv.gz}_hto.csv.gz
(
  zcat $csv | head -n1
  zcat $csv | tail -n+1 | grep "^HT"
) | gzip > $hto
```

```r
> f <- 'batch1_5p_adt_hto.csv.gz'
> d <- fread(f)
> d[1:5,1:5]
   Antibody AAACCTGAGAAACCAT AAACCTGAGAAACCGC AAACCTGAGAAACCTA AAACCTGAGAAACGAG
1: HT_C0251                0                0               12                8
2: HT_C0252                0                0              189                6
3: HT_C0254                1                1             1055               15
4: HT_C0256                1                1               72             1440
5: HT_C0257                2                0               13                9
> sum(colSums(d[,2:ncol(d)]) == 0)
[1] 6514
```

**Pull request closed without merging**
